[tool.poetry]
name = "bt_studio"
version = "0.1.0"
description = ""
authors = ["hengxin.liu <hengxin.liu@inceptio.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
ray = {extras = ["tune"], version = "^2.55.1"}
dtaidistance = "^2.4.0"
optuna = "^4.8.0"
mlops = "^0.1.0"
stumpy = "^1.14.1"
statsmodels = "^0.14.6"
dotenv = "^0.9.9"
streamlit = "^1.57.0"
bokeh = "^3.9.0"
coremltools = "^9.0"
asitop = "^0.0.24"
prometheus-client = "^0.25.0"
joblib = "^1.5.3"
graphviz = "^0.21"
mlflow = "^3.13.0"
prefect = "^3.7.3"
scikit-learn = "^1.9.0"
bt-core = "0.4.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
# optional: make this your default source for all installs
priority = "primary"

[[tool.poetry.source]]
name = "devpi"
# url = "http://192.168.2.100:3141/bt_sdk/dev/+simple/"
url = "http://localhost:3141/bt_sdk/dev/+simple/"
# optional: make this your default source for all installs
priority = "supplemental"
