from __future__ import annotations

import json
import os
import re
import time
import traceback
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional

from .prompt import build_system_prompt, build_rl_context_prompt
from .harness import TwoStageAgentHarness, FeatureMiningResult
from bt_studio.compiler.ast import ast_fingerprint

from bt_studio.constant import LLM_RUN_DIR
from bt_studio.utils.io import atomic_save_json


class ReplayBuffer:

    def __init__(self, max_success: int = 10, max_failed: int = 10):
        self.max_success = max_success
        self.max_failed = max_failed
        self.successful_history: List[Dict[str, Any]] = []
        self.failed_history: List[Dict[str, Any]] = []
        self._seen_success_fps: set[str] = set()

    def add_success(self, item: Dict[str, Any]) -> None:
        ast_obj = item.get("ast")
        fp = ast_fingerprint(ast_obj) if ast_obj else ""

        # decouple 
        if fp and fp in self._seen_success_fps:
            return

        score = item.get("score")
        if score is None or not isinstance(score, (int, float)):
            item["score"] = -500.0

        self.successful_history.append(item)
        if fp:
            self._seen_success_fps.add(fp)

        self.successful_history.sort(
            key=lambda x: x.get("score") if isinstance(x.get("score"), (int, float)) else -9999.0,
            reverse=True,
        )
        if len(self.successful_history) > self.max_success:
            removed = self.successful_history.pop()
            rem_fp = ast_fingerprint(removed.get("ast"))
            self._seen_success_fps.discard(rem_fp)

    def add_failure(self, item: Dict[str, Any]) -> None:
        """FIFO Failure"""
        self.failed_history.insert(0, item)
        del self.failed_history[self.max_failed:]


class RLFeatureFlywheel:
    """
        LLM Hperthesis and generate -> Harness Test -> RL -> Dump
    """

    def __init__(
        self,
        llm_call_fn: Callable[[str, str], str],
        harness: TwoStageAgentHarness,
        max_depth: int = 4,
    ):
        self.llm_call_fn = llm_call_fn
        self.harness = harness
        self.max_depth = max_depth
        self.buffer = ReplayBuffer()
        self._step_counter = 0

    def _parse_llm_json(self, raw_text: str) -> Optional[Dict[str, Any]]:
        if not raw_text or not raw_text.strip():
            return None

        text = raw_text.strip()

        # 1. re ```json ... ``` / ``` ... ```
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            text = match.group(1).strip()
        else:
            first_brace = text.find("{")
            last_brace = text.rfind("}")
            if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
                text = text[first_brace : last_brace + 1].strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            # Handle possible trailing data issue
            try:
                # Find the very last brace
                last_brace = text.rfind("}")
                if last_brace != -1:
                    text = text[:last_brace + 1].strip()
                    return json.loads(text)
            except json.JSONDecodeError:
                pass
            print(f"[Flywheel] JSON 解析失败: {e} | 原始片段: {raw_text[:120]!r}")
            return None

    @staticmethod
    def _failure_reason(r: FeatureMiningResult) -> str:
        if r.stage1_prefilter is None:
            return "Rejected by compile / causal / depth guard"
        if not r.stage1_prefilter.passed:
            return f"Stage 1 prefilter: {r.stage1_prefilter.reason}"
        if r.stage2_eval is None:
            return "Stage 2 produced no eval result"
        return (
            f"Stage 2 walk-forward pass ratio {r.window_pass_ratio:.0%} below threshold "
            f"({r.stage2_eval.reason or 'statistical tests not passed'})"
        )

    def step(self, target_description: str, hf_lf: Any, dret_lf: Any) -> List[FeatureMiningResult]:
   
        self._step_counter += 1
        print("\n" + "=" * 80)
        print(f"[Flywheel] Step {self._step_counter} 开始迭代...")

        system_prompt = build_system_prompt(self.max_depth)
        user_prompt = build_rl_context_prompt(
            target_description,
            self.buffer.successful_history,
            self.buffer.failed_history,
        )

        try:
            raw_output = self.llm_call_fn(system_prompt, user_prompt)
        except Exception as e:
            print(f"[Flywheel] LLM 调用异常: {e}")
            return []

        agent_data = self._parse_llm_json(raw_output)
        if not agent_data:
            self.buffer.add_failure({
                "reason": "Invalid JSON format generated by LLM",
                "ast": {"error_raw": raw_output[:150]},
            })
            return []

        reasoning = agent_data.get("economic_reasoning", "")
        candidate_asts = agent_data.get("sub_features", [])
        hyp_id = agent_data.get("hypothesis_id", f"hyp_{self._step_counter}")

        print(f"[Flywheel] [{hyp_id}] candidates: {len(candidate_asts)}")

        if not candidate_asts or not isinstance(candidate_asts, list):
            self.buffer.add_failure({
                "reason": "Empty or non-list sub_features",
                "ast": {"hypothesis_id": hyp_id},
            })
            return []

        # Harness 
        try:
            results = self.harness.run(candidate_asts, hf_lf, dret_lf)
        except Exception as e:
            traceback.print_exc()
            for ast in candidate_asts:
                self.buffer.add_failure({
                    "reason": f"Harness runtime crash: {e}",
                    "ast": ast,
                })
            return []

        for r in results:
            target_ast = r.raw_ast
            if not target_ast:
                continue

            if r.stage2_passed:
                self.buffer.add_success({
                    "score": r.final_score,
                    "reasoning": reasoning,
                    "ast": target_ast,
                })
            else:
                self.buffer.add_failure({
                    "reason": self._failure_reason(r),
                    "ast": target_ast,
                })

        # Artifact
        self._persist_step(agent_data, results, target_description)

        return results

    def _persist_step(
        self,
        agent_data: Dict[str, Any],
        results: List[FeatureMiningResult],
        target: str,
    ) -> None:
        
        try:
            os.makedirs(LLM_RUN_DIR, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            hyp = agent_data.get("hypothesis_id", "unknown")
            step_id = f"step_{ts}_{hyp}_s{self._step_counter}"

            rec = {
                "step_index": self._step_counter,
                "timestamp": ts,
                "target": target,
                "hypothesis_id": hyp,
                "economic_reasoning": agent_data.get("economic_reasoning", ""),
                "candidates": agent_data.get("sub_features", []),
                "features": [r.to_summary() for r in results],
                "replay_buffer": {
                    "n_success": len(self.buffer.successful_history),
                    "n_failure": len(self.buffer.failed_history),
                },
            }

            path = os.path.join(LLM_RUN_DIR, f"{step_id}.json")
            atomic_save_json(rec, path)
            print(f"[Flywheel] Artifact Save to: {path}")
        except Exception as e:
            print(f"[Flywheel] Artifact Error: {e}")
